"""
Report server integration — persist and serve genealogy reports via HTTP.

Wraps khonliang's reporting module with genealogy-specific theming and
detection. Reports generated by ReportBuilder are automatically persisted
and served as styled HTML pages.

Usage:
    from genealogy_agent.report_server import start_report_server, publish_report

    # Start the server (background thread)
    report_mgr = start_report_server(config)

    # Publish a report from ReportBuilder output
    url = publish_report(report_mgr, markdown, title="Smith Lineage", created_by="researcher")
"""

import logging
import threading
from pathlib import Path
from typing import Any, Dict, Optional

from khonliang.reporting import ReportDetector, ReportManager, ReportTheme
from khonliang.reporting.server import ReportServer

logger = logging.getLogger(__name__)

ASSETS_DIR = str(Path(__file__).parent.parent / "assets")


def create_theme(config: Dict[str, Any]) -> ReportTheme:
    """Build a ReportTheme from the genealogy config.yaml theme section."""
    theme_cfg = config.get("theme", {})
    return ReportTheme(
        name=config.get("app", {}).get("title", "Genealogy Agent"),
        logo_url="/static/logo.png",
        logo_height="48px",
        primary_color=theme_cfg.get("primary", "#6d28d9"),
        secondary_color=theme_cfg.get("border", "#5b21b6"),
        background_color=theme_cfg.get("background", "#f5f5f5"),
        card_background=theme_cfg.get("surface", "#ffffff"),
        text_color=theme_cfg.get("text", "#333333"),
        footer_text=config.get("app", {}).get("title", "Genealogy Agent"),
    )


def create_detector() -> ReportDetector:
    """Build a genealogy-tuned report detector."""
    detector = ReportDetector(
        analysis_keywords=[
            "ancestor", "descendant", "lineage", "genealogy",
            "census", "birth", "death", "marriage", "immigration",
            "family", "generation", "pedigree", "surname", "record",
            "research", "findings", "dead end", "gap",
        ],
        min_keywords=2,
        min_length=200,
        report_type_rules={
            "family_tree": ["ancestor", "descendant", "lineage", "pedigree", "generation"],
            "census_record": ["census", "household", "enumeration", "dwelling", "occupation"],
            "vital_record": ["birth", "death", "marriage", "baptism", "burial"],
            "immigration": ["immigration", "naturalization", "passenger", "ship", "port"],
            "gap_analysis": ["dead end", "gap", "missing", "incomplete", "anomaly"],
            "person_report": ["report", "tree data", "family summary", "research findings"],
            "research_summary": ["research", "findings", "summary", "evidence", "conclusion"],
        },
    )
    return detector


# Module-level singletons
_manager: Optional[ReportManager] = None
_detector: Optional[ReportDetector] = None
_server: Optional[ReportServer] = None


def get_manager() -> Optional[ReportManager]:
    """Get the module-level ReportManager, or None if not started."""
    return _manager


def get_detector() -> Optional[ReportDetector]:
    """Get the module-level ReportDetector."""
    global _detector
    if _detector is None:
        _detector = create_detector()
    return _detector


def publish_report(
    markdown: str,
    title: str,
    created_by: str = "agent",
    report_type: Optional[str] = None,
    metadata: Optional[Dict[str, Any]] = None,
    chat_context: Optional[Dict[str, Any]] = None,
) -> Optional[str]:
    """
    Persist a report and return its URL.

    Args:
        markdown: Report content in markdown.
        title: Human-readable title.
        created_by: Agent or role that generated it.
        report_type: Explicit type. Auto-detected if omitted.
        metadata: Extra metadata dict.
        chat_context: Chat integration linkback data.

    Returns:
        Report URL string, or None if reporting is not enabled.
    """
    if _manager is None or _server is None:
        return None

    detector = get_detector()
    if report_type is None:
        report_type = detector.detect_type(markdown)

    report = _manager.create(
        title=title,
        content_markdown=markdown,
        report_type=report_type,
        created_by=created_by,
        metadata=metadata,
        chat_context=chat_context,
    )

    url = _server.report_url(report.id)
    logger.info(f"Report published: {title} -> {url}")
    return url


def start_report_server(config: Dict[str, Any]) -> Optional[ReportManager]:
    """
    Start the report HTTP server in a background thread.

    Args:
        config: Full genealogy config dict.

    Returns:
        The ReportManager instance, or None if reporting is disabled.
    """
    global _manager, _server

    reports_cfg = config.get("reports", {})
    if not reports_cfg.get("enabled", False):
        logger.info("Report server disabled in config")
        return None

    db_path = reports_cfg.get("db", "data/reports.db")
    port = reports_cfg.get("port", 5050)
    host = config.get("server", {}).get("host", "0.0.0.0")

    theme = create_theme(config)
    _manager = ReportManager(db_path)

    _server = ReportServer(
        _manager,
        host=host,
        port=port,
        theme=theme,
        static_dir=ASSETS_DIR,
    )

    thread = threading.Thread(
        target=_server.run,
        daemon=True,
        name="report-server",
    )
    thread.start()

    logger.info(f"Report server: http://{host}:{port}/reports")
    return _manager
